<a href="https://colab.research.google.com/github/jiruneko/practical-machine-learning/blob/main/Deeplearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame(
  {
      'A':[1,2,3,4,np.nan],
      'B':[10, np.nan, 30, 40, 50],
      'C':[np.nan, 200, 300, 400, 500]
  }
)
df

A     B      C
0  1.0  10.0    NaN
1  2.0   NaN  200.0
2  3.0  30.0  300.0
3  4.0  40.0  400.0
4  NaN  50.0  500.0

In [ ]:
df.isnull()

A      B      C
0  False  False   True
1  False   True  False
2  False  False  False
3  False  False  False
4   True  False  False

In [ ]:
df.dropna()

A     B      C
2  3.0  30.0  300.0
3  4.0  40.0  400.0

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imp = SimpleImputer(strategy='mean')

In [ ]:
imp.fit(df)

SimpleImputer()

In [ ]:
imp.transform(df)

array([[  1. ,  10. , 350. ],
       [  2. ,  32.5, 200. ],
       [  3. ,  30. , 300. ],
       [  4. ,  40. , 400. ],
       [  2.5,  50. , 500. ]])

In [ ]:
from sklearn.impute import SimpleImputer
imp = SimpleImputer(strategy='mean')
imp.fit(df)
imp.transform(df)

array([[  1. ,  10. , 350. ],
       [  2. ,  32.5, 200. ],
       [  3. ,  30. , 300. ],
       [  4. ,  40. , 400. ],
       [  2.5,  50. , 500. ]])

In [ ]:
df = pd.DataFrame([[23, 'male'],
                   [43, 'female'],
                   [31, 'male'],
                   [35, 'female'],
                   [40, 'male']],
                  columns=['age', 'sex'])
df

age     sex
0   23    male
1   43  female
2   31    male
3   35  female
4   40    male

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
le = LabelEncoder()

In [ ]:
le.fit(df['sex'])

LabelEncoder()

In [ ]:
le.transform(df['sex'])

array([1, 0, 1, 0, 1])

In [ ]:
le.classes_

array(['female', 'male'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['sex'])
le.transform(df['sex'])

array([1, 0, 1, 0, 1])

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
ohe = ColumnTransformer([("OneHotEncoder", OneHotEncoder(), [1])], remainder='passthrough')

In [ ]:
df_ohe = df.copy()
ohe.fit_transform(df_ohe)

array([[ 0.,  1., 23.],
       [ 1.,  0., 43.],
       [ 0.,  1., 31.],
       [ 1.,  0., 35.],
       [ 0.,  1., 40.]])